version: '2'
services:
  app:
    image: 387451676619.dkr.ecr.us-west-2.amazonaws.com/whiteboard
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '80:3000'
    links:
      - mysql
    mem_limit: 268435456
  mysql:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    mem_limit: 268435456
volumes:
  mysql-data:
    driver: local
