version: '2'
services:
  app:
    build: ./
    environment:
      RAILS_ENV: production 
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
      AMAZONSES_USERNAME: 'username'
      AMAZONSES_PASSWORD: 'password'
      FROM_ADDRESS: 'xxx@example.com'
      HOST: 'host'
      SECRET_KEY_BASE: 'secret'
      RAILS_LOG_TO_STDOUT: 'true'
      ACCEPT_PASS: 'accept pass'
      S3_ACCESS_KEY: 'xxxxx'
      S3_BUCKET: 's3 bucket name'
      S3_REGION: 'us-west-2'
      S3_SECRET_KEY: 'xxxxx'
    ports:
      - '3000:3000'
    links:
      - mysql
    mem_limit: 268435456
    command: bash -c "bundle exec rake assets:precompile assets:clean db:create db:migrate && bundle exec puma -C config/puma.rb"
  web:
    build:
      context: containers/nginx
    ports:
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      # ローカルでオレオレ証明書などで試す場合はそのパスを記載する
      # - /path/to/crt:/path/to/crt
      # - /path/to/key:/path/to/key
    volumes_from:
      - app
    depends_on:
      - app
    mem_limit: 268435456
  mysql:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    mem_limit: 268435456
volumes:
  mysql-data:
    driver: local
