test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
production:
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
  database: whitboard
  url: <%= ENV['DATABASE_URL'] %>
